### ISSUE TITLE
PE0002.rb

### ISSUE THREAD

**Issue by MichaelVessia** [adelphimathcs/ProjectEuler-0002#2]
@MattMatero, very minor.. but i just remembered ruby has Fixnum#even? and Fixnum#odd?.  It's more idiomatic that n % 2 != 0.  I'm certainly guilty of this on many things i've coded.  but good to keep in mind for the future.

**Comment by MattMatero** [comment]
Fixed. Ty! do you think  
! Fixnum.even? or Fixnum.odd? would be more clear for the situation? Right now I have
unless !get_fib.even? but i think the unless and the negative leads to confusion for logic. opinion?

**Comment by MattMatero** [comment]
Decided to do unless fixnum.odd? cause it seems more natural. Let me know on your take.

**Comment by MichaelVessia** [comment]
I agree with your choice, as does the Ruby Style Guide.

https://github.com/bbatsov/ruby-style-guide#unless-for-negatives
